improper url

diff --git a/.github/workflows/multi-db-integration-test.yaml b/.github/workflows/multi-db-integration-test.yaml
--- a/.github/workflows/multi-db-integration-test.yaml
+++ b/.github/workflows/multi-db-integration-test.yaml
@@ -37,6 +37,8 @@ jobs:
         # create kubernetes secret for use by iter8-analytics
         kubectl create secret generic test-secret --from-literal=user=abcd --from-literal=pass=efgh
         kubectl apply -f iter8_analytics/tests/integration/secret-reader.yaml
+    - run: |
+        # curl metrics endpoint of analytics with metrics inputs... try proper URLs
         curl -X POST "http://localhost:8080/v2/aggregated_metrics" -H  "accept: application/json" -H  "Content-Type: application/json" -d @iter8_analytics/tests/integration/data/inputs/metrics1.json > out.json
         cat out.json
         echo "logging iter8 analytics"
@@ -44,10 +46,19 @@ jobs:
         echo "logging metrics mock"
         kubectl logs deploy/metrics-mock
         cat out.json | jq '.data | ."request-count".data.default.value | tonumber'
-
-    # curl metrics endpoint of analytics with proper metrics inputs... 
-    # try proper URLs
-    # try improper URLs
+    - run: |
+        # curl metrics endpoint of analytics with metrics inputs... try improper URLs
+        curl -X POST "http://localhost:8080/v2/aggregated_metrics" -H  "accept: application/json" -H  "Content-Type: application/json" -d @iter8_analytics/tests/integration/data/inputs/metrics2.json > out.json
+        cat out.json
+        echo "logging iter8 analytics"
+        kubectl logs deploy/iter8-analytics
+        echo "logging metrics mock"
+        kubectl logs deploy/metrics-mock
+        if cat out.json | jq '.data | ."request-count".data.default.value | tonumber'; then
+            echo "command succeeded unexpectedly..."
+            exit 1
+        else
+            echo "command failed as expected..."
     # try with proper headers
     # try without proper headers
     # try proper versions
