trying with improper versions

diff --git a/.github/workflows/multi-db-integration-test.yaml b/.github/workflows/multi-db-integration-test.yaml
--- a/.github/workflows/multi-db-integration-test.yaml
+++ b/.github/workflows/multi-db-integration-test.yaml
@@ -72,5 +72,16 @@ jobs:
             exit 1
         else
             echo "command failed as expected..."
-    # try proper versions
-    # try improper versions
+    - run: |
+        # curl metrics endpoint of analytics with metrics inputs... try improper versions
+        curl -X POST "http://localhost:8080/v2/aggregated_metrics" -H  "accept: application/json" -H  "Content-Type: application/json" -d @iter8_analytics/tests/integration/data/inputs/metrics4.json > out.json
+        cat out.json
+        echo "logging iter8 analytics"
+        kubectl logs deploy/iter8-analytics
+        echo "logging metrics mock"
+        kubectl logs deploy/metrics-mock
+        if cat out.json | jq '.data | ."request-count".data.default.value | tonumber'; then
+            echo "command succeeded unexpectedly..."
+            exit 1
+        else
+            echo "command failed as expected..."
